# https://cloud.google.com/appengine/docs/standard/python3/building-app
runtime: python
env: flex

entrypoint: gunicorn -b :8080 --worker-class eventlet -w 1 main:app

runtime_config:
  python_version: 3

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
  
manual_scaling:
  instances: 1

network:
  session_affinity: true
