# https://cloud.google.com/appengine/docs/standard/python3/building-app
runtime: python39
env: flex

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

manual_scaling:
  instances: 1